# coding: utf-8

"""
    Simple API

    A simple API to learn how to write OpenAPI Specification

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.metadata import Metadata


class TestMetadata(unittest.TestCase):
    """ Metadata unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadata(self):
        """
        Test Metadata
        """
        model = swagger_client.models.metadata.Metadata()


if __name__ == '__main__':
    unittest.main()
