# coding: utf-8

"""
    Simple API

    A simple API to learn how to write OpenAPI Specification

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_namespaces_namespace_repos_repo_name_get(self):
        """
        Test case for namespaces_namespace_repos_repo_name_get

        Gets a Repo in a Namespace
        """
        pass

    def test_repos_get(self):
        """
        Test case for repos_get

        Gets Repos
        """
        pass


if __name__ == '__main__':
    unittest.main()
