# coding: utf-8

"""
    kubeRepo

    Manage Third Party Resources from k8s

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kube_repo
from kube_repo.rest import ApiException
from kube_repo.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = kube_repo.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_apis_git_k8s_com_v1_namespaces_namespace_repos_name_get(self):
        """
        Test case for apis_git_k8s_com_v1_namespaces_namespace_repos_name_get

        Gets a specific Repo
        """
        pass

    def test_apis_git_k8s_com_v1_repos_get(self):
        """
        Test case for apis_git_k8s_com_v1_repos_get

        Gets Repos
        """
        pass


if __name__ == '__main__':
    unittest.main()
