# coding: utf-8

"""
    Simple API

    A simple API to learn how to write OpenAPI Specification

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.repo import Repo


class TestRepo(unittest.TestCase):
    """ Repo unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepo(self):
        """
        Test Repo
        """
        model = swagger_client.models.repo.Repo()


if __name__ == '__main__':
    unittest.main()
